const AllGenders = [
  "WOMAN",
  "MAN",
  "NON_BINARY",
  "TRANS_WOMAN",
  "TRANS_MAN",
  "GENDER_FLUID",
  "AGENDER",
  "OTHER",
];

const GenderEveryone = "EVERYONE";

const AllQuestions = [
  "weird_normal",
  "current_life",
  "alone_time",
  "planning",
  "small_talk",
  "looks",
  "smoking",
  "drinking",
  "meals",
  "diet",
  "health",
  "physical_activity",
  "mindfulness",
  "minimalism",
  "spectrum",
  "environment",
  "racial",
  "gender_equality",
  "LGBTQIA+",
  "importance_comfort_friend",
  "emotions",
  "self_reflective",
  "conflicts_self",
  "conflicts_partner",
  "support_need",
  "support_offer",
  "indoor_outdoor",
  "spend_free_time",
  "do_with_friends",
  "new_activities",
  "vacation",
  "aeroplane",
  "conversation_topics",
  "social_media",
  "pets",
  "religion_importance",
  "same_religion",
];

module.exports = { AllGenders, GenderEveryone, AllQuestions };
