const AllGenders = [
  "WOMAN",
  "MAN",
  "NON_BINARY",
  "TRANS_WOMAN",
  "TRANS_MAN",
  "GENDER_FLUID",
  "AGENDER",
];

const GenderEveryone = "EVERYONE";

const AllQuestions = [
  "relationship",
  "see_partner",
  "current_life",
  "alone_time",
  "small_talk",
  "looks",
  "smoking",
  "drinking",
  "meals",
  "diet",
  "health",
  "physical_activity",
  "mindfulness",
  "minimalism",
  "spectrum",
  "environment",
  "racial",
  "gender_equality",
  "LGBTQIA+",
  "improving",
  "improvement_focus",
  "importance_comfort",
  "emotions",
  "conflicts_self",
  "conflicts_partner",
  "support_need",
  "support_offer",
  "indoor_outdoor",
  "spend_free_time",
  "do_with_friends",
  "new_activities",
  "vacation",
  "planning",
  "conversation_topics",
  "social_media",
  "kids",
  "when_kids",
  "parenting",
  "pets",
  "religion_importance",
  "same_religion",
];

module.exports = { AllGenders, GenderEveryone, AllQuestions };
