name: Flutter CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          cache: true
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          pub-cache-key: 'flutter-pub:os:-:channel:-:version:-:arch:-:hash:'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Ensure this job runs only on push to main, not on pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          cache: true
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          pub-cache-key: 'flutter-pub:os:-:channel:-:version:-:arch:-:hash:'

      - name: Flutter Build Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEEP_CONNECTIONS_7796D }}'
          channelId: live
          projectId: deep-connections-7796d
