name: Firebase CI

on: [ push ]

jobs:
  firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: NPM install
        working-directory: ./firebase
        run: npm install

      - name: Firebase emulator test
        run: |
          npm install -g firebase-tools
          firebase emulators:exec --only firestore 'cd firebase && npm test'