# name: CI

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '20'

#     - name: Cache node modules for firebase
#       uses: actions/cache@v2
#       with:
#         path: firebase/node_modules
#         key: ${{ runner.os }}-node-firebase-${{ hashFiles('firebase/package-lock.json') }}
#         restore-keys: |
#           ${{ runner.os }}-node-firebase-

#     - name: Install dependencies for firebase
#       run: npm ci
#       working-directory: firebase

#     - name: Run build for firebase
#       run: npm run build
#       working-directory: firebase